import type { Access, PassId, Resort } from './types'

// 2026-27 Ikon roster, and the single place to correct access data -- nothing
// else hardcodes one. Alterra adjusts both the roster and the blackout
// calendar between announcement and season, and secondary sources disagree on
// the details, so treat ikonpass.com as authoritative.

const unlimited = (note?: string): Access => ({ kind: 'unlimited', blackouts: false, note })
/** Unlimited access that still honours the holiday blackout calendar. */
const unlimitedBlackout = (note?: string): Access => ({ kind: 'unlimited', blackouts: true, note })
const days = (n: number, blackouts = true, note?: string): Access => ({
  kind: 'days',
  days: n,
  blackouts,
  note,
})

/** Full Ikon + Base at the same shape (most partner resorts: 7 vs 5 days). */
const both = (
  full: Access,
  base: Access | null,
): Partial<Record<PassId, Access>> => (base ? { ikon: full, 'ikon-base': base } : { ikon: full })

/** Full-Ikon only -- the Base tier does not reach this mountain at all. */
const fullOnly = (full: Access): Partial<Record<PassId, Access>> => ({ ikon: full })

export const BASE_BLACKOUT_DATES = [
  { range: '26-30 Dec 2026', label: 'Holiday' },
  { range: '16-17 Jan 2027', label: 'MLK' },
  { range: '13-14 Feb 2027', label: "Presidents'" },
]

export const RESORTS: Resort[] = [
  {
    id: 'palisades-tahoe',
    name: 'Palisades Tahoe',
    locale: 'California',
    country: 'USA',
    region: 'us-west',
    macro: 'us',
    lat: 39.1970,
    lon: -120.2357,
    baseElevationFt: 6200,
    summitElevationFt: 9050,
    avgAnnualSnowIn: 400,
    ensoSensitivity: 0.55,
    access: both(unlimitedBlackout(), days(5)),
    website: 'https://www.palisadestahoe.com',
  },
  {
    id: 'mammoth',
    name: 'Mammoth Mountain',
    locale: 'California',
    country: 'USA',
    region: 'us-west',
    macro: 'us',
    lat: 37.6308,
    lon: -119.0326,
    baseElevationFt: 7953,
    summitElevationFt: 11053,
    avgAnnualSnowIn: 400,
    ensoSensitivity: 0.72,
    access: both(unlimitedBlackout(), days(5)),
    website: 'https://www.mammothmountain.com',
  },
  {
    id: 'june-mountain',
    name: 'June Mountain',
    locale: 'California',
    country: 'USA',
    region: 'us-west',
    macro: 'us',
    lat: 37.7700,
    lon: -119.0900,
    baseElevationFt: 7545,
    summitElevationFt: 10090,
    avgAnnualSnowIn: 250,
    ensoSensitivity: 0.70,
    access: both(unlimited(), unlimited()),
    website: 'https://www.junemountain.com',
  },
  {
    id: 'big-bear',
    name: 'Big Bear Mountain Resort',
    locale: 'California',
    country: 'USA',
    region: 'us-southwest',
    macro: 'us',
    lat: 34.2364,
    lon: -116.8892,
    baseElevationFt: 7140,
    summitElevationFt: 8805,
    avgAnnualSnowIn: 100,
    ensoSensitivity: 0.90,
    access: both(unlimited(), days(5)),
    website: 'https://www.bigbearmountainresort.com',
  },
  {
    id: 'snow-valley',
    name: 'Snow Valley',
    locale: 'California',
    country: 'USA',
    region: 'us-southwest',
    macro: 'us',
    lat: 34.2214,
    lon: -117.0350,
    baseElevationFt: 6800,
    summitElevationFt: 7841,
    avgAnnualSnowIn: 90,
    ensoSensitivity: 0.90,
    access: both(unlimited(), days(5)),
    // Part of Big Bear Mountain Resort since 2023. snow-valley.com is now only
    // a redirect here, and its HTTPS listener hangs, so link the operator.
    website: 'https://www.bigbearmountainresort.com',
  },
  {
    id: 'alta',
    name: 'Alta',
    locale: 'Utah',
    country: 'USA',
    region: 'us-west',
    macro: 'us',
    lat: 40.5883,
    lon: -111.6358,
    baseElevationFt: 8530,
    summitElevationFt: 10550,
    avgAnnualSnowIn: 547,
    ensoSensitivity: 0.45,
    access: fullOnly(unlimitedBlackout()),
    website: 'https://www.alta.com',
  },
  {
    id: 'snowbird',
    name: 'Snowbird',
    locale: 'Utah',
    country: 'USA',
    region: 'us-west',
    macro: 'us',
    lat: 40.5810,
    lon: -111.6556,
    baseElevationFt: 8100,
    summitElevationFt: 11000,
    avgAnnualSnowIn: 500,
    ensoSensitivity: 0.45,
    access: both(unlimitedBlackout(), days(5, true, 'Snowbird only -- no Alta at the Base tier')),
    website: 'https://www.snowbird.com',
  },
  {
    id: 'solitude',
    name: 'Solitude',
    locale: 'Utah',
    country: 'USA',
    region: 'us-west',
    macro: 'us',
    lat: 40.6199,
    lon: -111.5919,
    baseElevationFt: 7994,
    summitElevationFt: 10488,
    avgAnnualSnowIn: 500,
    ensoSensitivity: 0.45,
    access: both(unlimited(), unlimited('No day limit, no blackouts')),
    website: 'https://www.solitudemountain.com',
  },
  {
    id: 'brighton',
    name: 'Brighton',
    locale: 'Utah',
    country: 'USA',
    region: 'us-west',
    macro: 'us',
    lat: 40.5977,
    lon: -111.5836,
    baseElevationFt: 8755,
    summitElevationFt: 10500,
    avgAnnualSnowIn: 500,
    ensoSensitivity: 0.45,
    access: both(unlimited(), days(5)),
    website: 'https://www.brightonresort.com',
  },
  {
    id: 'deer-valley',
    name: 'Deer Valley',
    locale: 'Utah',
    country: 'USA',
    region: 'us-west',
    macro: 'us',
    lat: 40.6374,
    lon: -111.4783,
    baseElevationFt: 6570,
    summitElevationFt: 9570,
    avgAnnualSnowIn: 300,
    ensoSensitivity: 0.42,
    access: fullOnly(unlimitedBlackout()),
    website: 'https://www.deervalley.com',
  },
  {
    id: 'snowbasin',
    name: 'Snowbasin',
    locale: 'Utah',
    country: 'USA',
    region: 'us-west',
    macro: 'us',
    lat: 41.2160,
    lon: -111.8569,
    baseElevationFt: 6450,
    summitElevationFt: 9350,
    avgAnnualSnowIn: 300,
    ensoSensitivity: 0.30,
    access: fullOnly(days(7)),
    website: 'https://www.snowbasin.com',
  },
  {
    id: 'aspen-snowmass',
    name: 'Snowmass',
    locale: 'Colorado',
    country: 'USA',
    region: 'us-rockies',
    macro: 'us',
    lat: 39.2097,
    lon: -106.9497,
    baseElevationFt: 8104,
    summitElevationFt: 12510,
    avgAnnualSnowIn: 300,
    ensoSensitivity: 0.18,
    access: both(days(7), days(5, true, 'Snowmass only -- the other three Aspen mountains are full-Ikon')),
    website: 'https://www.aspensnowmass.com',
  },
  {
    id: 'arapahoe-basin',
    name: 'Arapahoe Basin',
    locale: 'Colorado',
    country: 'USA',
    region: 'us-rockies',
    macro: 'us',
    lat: 39.6425,
    lon: -105.8719,
    baseElevationFt: 10780,
    summitElevationFt: 13050,
    avgAnnualSnowIn: 350,
    ensoSensitivity: 0.10,
    access: both(unlimited(), unlimited('New for 2026-27; spring access runs to 6 Apr')),
    website: 'https://www.arapahoebasin.com',
  },
  {
    id: 'copper',
    name: 'Copper Mountain',
    locale: 'Colorado',
    country: 'USA',
    region: 'us-rockies',
    macro: 'us',
    lat: 39.5022,
    lon: -106.1497,
    baseElevationFt: 9712,
    summitElevationFt: 12313,
    avgAnnualSnowIn: 305,
    ensoSensitivity: 0.08,
    access: both(unlimitedBlackout(), days(5)),
    website: 'https://www.coppercolorado.com',
  },
  {
    id: 'winter-park',
    name: 'Winter Park',
    locale: 'Colorado',
    country: 'USA',
    region: 'us-rockies',
    macro: 'us',
    lat: 39.8868,
    lon: -105.7625,
    baseElevationFt: 9000,
    summitElevationFt: 12060,
    avgAnnualSnowIn: 327,
    ensoSensitivity: 0.05,
    access: both(unlimitedBlackout(), days(5)),
    website: 'https://www.winterparkresort.com',
  },
  {
    id: 'steamboat',
    name: 'Steamboat',
    locale: 'Colorado',
    country: 'USA',
    region: 'us-rockies',
    macro: 'us',
    lat: 40.4572,
    lon: -106.8045,
    baseElevationFt: 6900,
    summitElevationFt: 10568,
    avgAnnualSnowIn: 314,
    ensoSensitivity: -0.05,
    access: both(unlimitedBlackout(), days(5)),
    website: 'https://www.steamboat.com',
  },
  {
    id: 'eldora',
    name: 'Eldora',
    locale: 'Colorado',
    country: 'USA',
    region: 'us-rockies',
    macro: 'us',
    lat: 39.9372,
    lon: -105.5827,
    baseElevationFt: 9200,
    summitElevationFt: 10800,
    avgAnnualSnowIn: 300,
    ensoSensitivity: 0.05,
    access: both(unlimited(), days(5)),
    website: 'https://www.eldora.com',
  },
  {
    id: 'taos',
    name: 'Taos Ski Valley',
    locale: 'New Mexico',
    country: 'USA',
    region: 'us-southwest',
    macro: 'us',
    lat: 36.5951,
    lon: -105.4506,
    baseElevationFt: 9200,
    summitElevationFt: 12481,
    avgAnnualSnowIn: 300,
    ensoSensitivity: 0.85,
    access: both(days(7), days(5)),
    website: 'https://www.skitaos.com',
  },
  {
    id: 'jackson-hole',
    name: 'Jackson Hole',
    locale: 'Wyoming',
    country: 'USA',
    region: 'us-rockies',
    macro: 'us',
    lat: 43.5875,
    lon: -110.8279,
    baseElevationFt: 6311,
    summitElevationFt: 10450,
    avgAnnualSnowIn: 459,
    ensoSensitivity: -0.35,
    access: fullOnly(days(7)),
    website: 'https://www.jacksonhole.com',
  },
  {
    id: 'big-sky',
    name: 'Big Sky',
    locale: 'Montana',
    country: 'USA',
    region: 'us-rockies',
    macro: 'us',
    lat: 45.2856,
    lon: -111.4010,
    baseElevationFt: 7500,
    summitElevationFt: 11166,
    avgAnnualSnowIn: 400,
    ensoSensitivity: -0.20,
    access: both(days(7), days(5)),
    website: 'https://www.bigskyresort.com',
  },
  {
    id: 'sun-valley',
    name: 'Sun Valley',
    locale: 'Idaho',
    country: 'USA',
    region: 'us-rockies',
    macro: 'us',
    lat: 43.6963,
    lon: -114.3717,
    baseElevationFt: 5750,
    summitElevationFt: 9150,
    avgAnnualSnowIn: 200,
    ensoSensitivity: -0.10,
    access: fullOnly(days(7)),
    website: 'https://www.sunvalley.com',
  },
  {
    id: 'schweitzer',
    name: 'Schweitzer',
    locale: 'Idaho',
    country: 'USA',
    region: 'us-pnw',
    macro: 'us',
    lat: 48.3686,
    lon: -116.6228,
    baseElevationFt: 4700,
    summitElevationFt: 6400,
    avgAnnualSnowIn: 300,
    ensoSensitivity: -0.45,
    access: both(days(7), days(5)),
    website: 'https://www.schweitzer.com',
  },
  {
    id: 'crystal-mountain',
    name: 'Crystal Mountain',
    locale: 'Washington',
    country: 'USA',
    region: 'us-pnw',
    macro: 'us',
    lat: 46.9282,
    lon: -121.4746,
    baseElevationFt: 4400,
    summitElevationFt: 7012,
    avgAnnualSnowIn: 486,
    ensoSensitivity: -0.60,
    access: both(days(7), days(5)),
    website: 'https://www.crystalmountainresort.com',
  },
  {
    id: 'snoqualmie',
    name: 'The Summit at Snoqualmie',
    locale: 'Washington',
    country: 'USA',
    region: 'us-pnw',
    macro: 'us',
    lat: 47.4243,
    lon: -121.4137,
    baseElevationFt: 3000,
    summitElevationFt: 5420,
    avgAnnualSnowIn: 428,
    ensoSensitivity: -0.65,
    access: both(days(7), days(5)),
    website: 'https://summitatsnoqualmie.com',
  },
  {
    id: 'mt-bachelor',
    name: 'Mt. Bachelor',
    locale: 'Oregon',
    country: 'USA',
    region: 'us-pnw',
    macro: 'us',
    lat: 43.9793,
    lon: -121.6884,
    baseElevationFt: 6300,
    summitElevationFt: 9065,
    avgAnnualSnowIn: 462,
    ensoSensitivity: -0.45,
    access: both(unlimitedBlackout(), days(5)),
    website: 'https://www.mtbachelor.com',
  },
  {
    id: 'killington',
    name: 'Killington',
    locale: 'Vermont',
    country: 'USA',
    region: 'us-east',
    macro: 'us',
    lat: 43.6266,
    lon: -72.7962,
    baseElevationFt: 1165,
    summitElevationFt: 4241,
    avgAnnualSnowIn: 250,
    ensoSensitivity: -0.40,
    access: both(days(7), days(5)),
    website: 'https://www.killington.com',
  },
  {
    id: 'stratton',
    name: 'Stratton',
    locale: 'Vermont',
    country: 'USA',
    region: 'us-east',
    macro: 'us',
    lat: 43.1134,
    lon: -72.9082,
    baseElevationFt: 1872,
    summitElevationFt: 3875,
    avgAnnualSnowIn: 180,
    ensoSensitivity: -0.35,
    access: both(unlimitedBlackout(), days(5)),
    website: 'https://www.stratton.com',
  },
  {
    id: 'sugarbush',
    name: 'Sugarbush',
    locale: 'Vermont',
    country: 'USA',
    region: 'us-east',
    macro: 'us',
    lat: 44.1360,
    lon: -72.8939,
    baseElevationFt: 1483,
    summitElevationFt: 4083,
    avgAnnualSnowIn: 269,
    ensoSensitivity: -0.38,
    access: both(unlimitedBlackout(), days(5)),
    website: 'https://www.sugarbush.com',
  },
  {
    id: 'sunday-river',
    name: 'Sunday River',
    locale: 'Maine',
    country: 'USA',
    region: 'us-east',
    macro: 'us',
    lat: 44.4730,
    lon: -70.8567,
    baseElevationFt: 800,
    summitElevationFt: 3140,
    avgAnnualSnowIn: 167,
    ensoSensitivity: -0.40,
    access: both(unlimitedBlackout(), days(5)),
    website: 'https://www.sundayriver.com',
  },
  {
    id: 'sugarloaf',
    name: 'Sugarloaf',
    locale: 'Maine',
    country: 'USA',
    region: 'us-east',
    macro: 'us',
    lat: 45.0314,
    lon: -70.3131,
    baseElevationFt: 1417,
    summitElevationFt: 4237,
    avgAnnualSnowIn: 200,
    ensoSensitivity: -0.42,
    access: both(unlimitedBlackout(), days(5)),
    website: 'https://www.sugarloaf.com',
  },
  {
    id: 'loon',
    name: 'Loon Mountain',
    locale: 'New Hampshire',
    country: 'USA',
    region: 'us-east',
    macro: 'us',
    lat: 44.0564,
    lon: -71.6217,
    baseElevationFt: 950,
    summitElevationFt: 3050,
    avgAnnualSnowIn: 160,
    ensoSensitivity: -0.38,
    access: both(unlimitedBlackout(), days(5)),
    website: 'https://www.loonmtn.com',
  },
  {
    id: 'snowshoe',
    name: 'Snowshoe',
    locale: 'West Virginia',
    country: 'USA',
    region: 'us-east',
    macro: 'us',
    lat: 38.4120,
    lon: -79.9950,
    baseElevationFt: 3348,
    summitElevationFt: 4848,
    avgAnnualSnowIn: 180,
    ensoSensitivity: -0.10,
    access: both(unlimited(), days(5)),
    website: 'https://www.snowshoemtn.com',
  },
  {
    id: 'boyne-mountain',
    name: 'Boyne Mountain',
    locale: 'Michigan',
    country: 'USA',
    region: 'us-east',
    macro: 'us',
    lat: 45.1633,
    lon: -84.9314,
    baseElevationFt: 640,
    summitElevationFt: 1120,
    avgAnnualSnowIn: 140,
    ensoSensitivity: -0.50,
    access: both(unlimitedBlackout(), days(5)),
    website: 'https://www.boynemountain.com',
  },
  {
    id: 'the-highlands',
    name: 'The Highlands',
    locale: 'Michigan',
    country: 'USA',
    region: 'us-east',
    macro: 'us',
    lat: 45.4600,
    lon: -84.9300,
    baseElevationFt: 700,
    summitElevationFt: 1250,
    avgAnnualSnowIn: 140,
    ensoSensitivity: -0.50,
    access: both(unlimitedBlackout(), days(5)),
    website: 'https://www.highlandsharborsprings.com',
  },
  {
    id: 'revelstoke',
    name: 'Revelstoke',
    locale: 'British Columbia',
    country: 'Canada',
    region: 'canada-west',
    macro: 'canada',
    lat: 50.9581,
    lon: -118.1636,
    baseElevationFt: 1680,
    summitElevationFt: 7300,
    avgAnnualSnowIn: 414,
    ensoSensitivity: -0.55,
    access: both(days(7), days(5)),
    website: 'https://www.revelstokemountainresort.com',
  },
  {
    id: 'lake-louise',
    name: 'Lake Louise',
    locale: 'Alberta',
    country: 'Canada',
    region: 'canada-west',
    macro: 'canada',
    lat: 51.4419,
    lon: -116.1653,
    baseElevationFt: 5400,
    summitElevationFt: 8650,
    avgAnnualSnowIn: 179,
    ensoSensitivity: -0.50,
    access: both(days(7), days(5)),
    website: 'https://www.skilouise.com',
  },
  {
    id: 'sunshine-village',
    name: 'Banff Sunshine',
    locale: 'Alberta',
    country: 'Canada',
    region: 'canada-west',
    macro: 'canada',
    lat: 51.0784,
    lon: -115.7767,
    baseElevationFt: 5440,
    summitElevationFt: 8954,
    avgAnnualSnowIn: 360,
    ensoSensitivity: -0.50,
    access: both(days(7), days(5)),
    website: 'https://www.skibanff.com',
  },
  {
    id: 'fernie',
    name: 'Fernie',
    locale: 'British Columbia',
    country: 'Canada',
    region: 'canada-west',
    macro: 'canada',
    lat: 49.4625,
    lon: -115.0878,
    baseElevationFt: 3450,
    summitElevationFt: 6316,
    avgAnnualSnowIn: 360,
    ensoSensitivity: -0.40,
    access: both(days(7), days(5)),
    website: 'https://skifernie.com',
  },
  {
    id: 'kicking-horse',
    name: 'Kicking Horse',
    locale: 'British Columbia',
    country: 'Canada',
    region: 'canada-west',
    macro: 'canada',
    lat: 51.2980,
    lon: -117.0490,
    baseElevationFt: 3927,
    summitElevationFt: 8033,
    avgAnnualSnowIn: 291,
    ensoSensitivity: -0.50,
    access: both(days(7), days(5)),
    website: 'https://kickinghorseresort.com',
  },
  {
    id: 'sun-peaks',
    name: 'Sun Peaks',
    locale: 'British Columbia',
    country: 'Canada',
    region: 'canada-west',
    macro: 'canada',
    lat: 50.8833,
    lon: -119.8833,
    baseElevationFt: 3930,
    summitElevationFt: 6824,
    avgAnnualSnowIn: 237,
    ensoSensitivity: -0.50,
    access: both(days(7), days(5)),
    website: 'https://www.sunpeaksresort.com',
  },
  {
    id: 'red-mountain',
    name: 'RED Mountain',
    locale: 'British Columbia',
    country: 'Canada',
    region: 'canada-west',
    macro: 'canada',
    lat: 49.1050,
    lon: -117.8200,
    baseElevationFt: 3887,
    summitElevationFt: 6807,
    avgAnnualSnowIn: 300,
    ensoSensitivity: -0.40,
    access: both(days(7), days(5)),
    website: 'https://redresort.com',
  },
  {
    id: 'panorama',
    name: 'Panorama',
    locale: 'British Columbia',
    country: 'Canada',
    region: 'canada-west',
    macro: 'canada',
    lat: 50.4600,
    lon: -116.2400,
    baseElevationFt: 3084,
    summitElevationFt: 8038,
    avgAnnualSnowIn: 205,
    ensoSensitivity: -0.45,
    access: both(days(7), days(5)),
    website: 'https://www.panoramaresort.com',
  },
  {
    id: 'tremblant',
    name: 'Mont Tremblant',
    locale: 'Quebec',
    country: 'Canada',
    region: 'canada-east',
    macro: 'canada',
    lat: 46.2094,
    lon: -74.5850,
    baseElevationFt: 870,
    summitElevationFt: 2871,
    avgAnnualSnowIn: 150,
    ensoSensitivity: -0.45,
    access: both(days(7), days(5)),
    website: 'https://www.tremblant.ca',
  },
  {
    id: 'blue-mountain-on',
    name: 'Blue Mountain',
    locale: 'Ontario',
    country: 'Canada',
    region: 'canada-east',
    macro: 'canada',
    lat: 44.5017,
    lon: -80.3100,
    baseElevationFt: 750,
    summitElevationFt: 1450,
    avgAnnualSnowIn: 110,
    ensoSensitivity: -0.55,
    access: both(unlimitedBlackout(), days(5)),
    website: 'https://www.bluemountain.ca',
  },
  {
    id: 'mont-sainte-anne',
    name: 'Mont-Sainte-Anne',
    locale: 'Quebec',
    country: 'Canada',
    region: 'canada-east',
    macro: 'canada',
    lat: 47.0750,
    lon: -70.9050,
    baseElevationFt: 575,
    summitElevationFt: 2625,
    avgAnnualSnowIn: 160,
    ensoSensitivity: -0.45,
    access: both(days(7), days(5)),
    website: 'https://mont-sainte-anne.com',
  },
  {
    id: 'zermatt',
    name: 'Zermatt',
    locale: 'Valais',
    country: 'Switzerland',
    region: 'europe',
    macro: 'europe',
    lat: 46.0207,
    lon: 7.7491,
    baseElevationFt: 5265,
    summitElevationFt: 12792,
    avgAnnualSnowIn: 220,
    ensoSensitivity: 0.30,
    access: fullOnly(days(7)),
    website: 'https://www.zermatt.ch',
  },
  {
    id: 'chamonix',
    name: 'Chamonix Mont-Blanc',
    locale: 'Haute-Savoie',
    country: 'France',
    region: 'europe',
    macro: 'europe',
    lat: 45.9237,
    lon: 6.8694,
    baseElevationFt: 3396,
    summitElevationFt: 12605,
    avgAnnualSnowIn: 250,
    ensoSensitivity: 0.32,
    access: both(days(7), days(5)),
    website: 'https://www.chamonix.com',
  },
  {
    id: 'dolomiti-superski',
    name: 'Dolomiti Superski',
    locale: 'Dolomites',
    country: 'Italy',
    region: 'europe',
    macro: 'europe',
    lat: 46.5405,
    lon: 11.9410,
    baseElevationFt: 4000,
    summitElevationFt: 10370,
    avgAnnualSnowIn: 160,
    ensoSensitivity: 0.10,
    access: both(days(7), days(5)),
    website: 'https://www.dolomitisuperski.com',
  },
  {
    id: 'st-anton',
    name: 'St. Anton am Arlberg',
    locale: 'Tyrol',
    country: 'Austria',
    region: 'europe',
    macro: 'europe',
    lat: 47.1300,
    lon: 10.2683,
    baseElevationFt: 4265,
    summitElevationFt: 9222,
    avgAnnualSnowIn: 320,
    ensoSensitivity: 0.28,
    access: both(days(7), days(5)),
    website: 'https://www.stantonamarlberg.com',
  },
  {
    id: 'kitzbuhel',
    name: 'Kitzbuhel',
    locale: 'Tyrol',
    country: 'Austria',
    region: 'europe',
    macro: 'europe',
    lat: 47.4467,
    lon: 12.3917,
    baseElevationFt: 2600,
    summitElevationFt: 6560,
    avgAnnualSnowIn: 200,
    ensoSensitivity: 0.18,
    access: both(days(7), days(5)),
    website: 'https://www.kitzbueheler-alpen.com',
  },
  {
    id: 'grandvalira',
    name: 'Grandvalira',
    locale: 'Andorra',
    country: 'Andorra',
    region: 'europe',
    macro: 'europe',
    lat: 42.5400,
    lon: 1.6600,
    baseElevationFt: 3937,
    summitElevationFt: 8662,
    avgAnnualSnowIn: 150,
    ensoSensitivity: 0.20,
    access: both(days(7), days(5)),
    website: 'https://www.grandvalira.com',
  },
  {
    id: 'niseko',
    name: 'Niseko United',
    locale: 'Hokkaido',
    country: 'Japan',
    region: 'japan',
    macro: 'japan',
    lat: 42.8048,
    lon: 140.6874,
    baseElevationFt: 830,
    summitElevationFt: 3593,
    avgAnnualSnowIn: 590,
    ensoSensitivity: -0.30,
    access: both(days(7), days(5)),
    website: 'https://www.niseko.ne.jp',
  },
  {
    id: 'rusutsu',
    name: 'Rusutsu',
    locale: 'Hokkaido',
    country: 'Japan',
    region: 'japan',
    macro: 'japan',
    lat: 42.7333,
    lon: 140.9000,
    baseElevationFt: 1300,
    summitElevationFt: 3300,
    avgAnnualSnowIn: 550,
    ensoSensitivity: -0.30,
    access: both(days(7), days(5)),
    website: 'https://rusutsu.com',
  },
  {
    id: 'arai',
    name: 'Lotte Arai',
    locale: 'Niigata',
    country: 'Japan',
    region: 'japan',
    macro: 'japan',
    lat: 37.0300,
    lon: 138.3200,
    baseElevationFt: 1070,
    summitElevationFt: 3612,
    avgAnnualSnowIn: 630,
    ensoSensitivity: -0.55,
    access: both(days(7), days(5)),
    website: 'https://www.lottehotel.com/arai-resort',
  },
  {
    id: 'thredbo',
    name: 'Thredbo',
    locale: 'New South Wales',
    country: 'Australia',
    region: 'south-pacific',
    macro: 'southern',
    lat: -36.5047,
    lon: 148.3033,
    baseElevationFt: 4318,
    summitElevationFt: 6683,
    avgAnnualSnowIn: 120,
    ensoSensitivity: -0.25,
    access: both(days(7), days(5)),
    website: 'https://www.thredbo.com.au',
  },
  {
    id: 'mt-buller',
    name: 'Mt Buller',
    locale: 'Victoria',
    country: 'Australia',
    region: 'south-pacific',
    macro: 'southern',
    lat: -37.1467,
    lon: 146.4367,
    baseElevationFt: 4757,
    summitElevationFt: 5915,
    avgAnnualSnowIn: 110,
    ensoSensitivity: -0.25,
    access: both(days(7), days(5)),
    website: 'https://www.mtbuller.com.au',
  },
  {
    id: 'coronet-peak',
    name: 'Coronet Peak',
    locale: 'Otago',
    country: 'New Zealand',
    region: 'south-pacific',
    macro: 'southern',
    lat: -44.9200,
    lon: 168.7350,
    baseElevationFt: 3937,
    summitElevationFt: 5410,
    avgAnnualSnowIn: 120,
    ensoSensitivity: 0.15,
    access: both(days(7), days(5)),
    website: 'https://www.coronetpeak.co.nz',
  },
  {
    id: 'valle-nevado',
    name: 'Valle Nevado',
    locale: 'Santiago',
    country: 'Chile',
    region: 'south-america',
    macro: 'southern',
    lat: -33.3561,
    lon: -70.2483,
    baseElevationFt: 9840,
    summitElevationFt: 12040,
    avgAnnualSnowIn: 275,
    ensoSensitivity: 0.55,
    access: both(days(7), days(5)),
    website: 'https://vallenevado.com',
  },
]

export const RESORTS_BY_ID = new Map(RESORTS.map((r) => [r.id, r]))

/** Resorts a given pass tier actually reaches. */
export function resortsForPass(pass: PassId): Resort[] {
  return RESORTS.filter((r) => r.access[pass] !== undefined)
}
